cameras:
  - id: camera1
    rtsp_url: "rtsp://your_camera1"
  - id: camera2
    rtsp_url: "rtsp://your_camera2"

detector:
  model_path: "yolov8n.pt"
  confidence_threshold: 0.5
  person_class_id: 0

tracker:
  max_age: 30
  min_hits: 3
  iou_threshold: 0.3
  
reid:
  model_name: "resnet18"
  
redis:
  host: "localhost"
  port: 6379
  db: 0